name: CMake Build

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  actions: read

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: x64
            msvc_arch: x64
          - arch: x86
            msvc_arch: x86
          - arch: arm64
            msvc_arch: amd64_arm64
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 1) Bootstrap the VS 2022 developer environment so that cl.exe is on PATH
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
       arch: ${{ matrix.msvc_arch }}

    - name: Configure CMake
      run: cmake --preset ${{ matrix.arch }}-release
      
    - name: Build
      run: cmake --build build/${{ matrix.arch }}-release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BigPictureSwitch-${{ matrix.arch }}-${{ github.sha }}
        path: |
          build/${{ matrix.arch }}-release/BigPictureSwitch.exe
          build/${{ matrix.arch }}-release/BigPictureSwitch.pdb
        retention-days: 30

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: BigPictureSwitch-*-${{ github.sha }}
        merge-multiple: false
    
    - name: Create Release Packages
      run: |
        # Package x64 build
        Compress-Archive -Path BigPictureSwitch-x64-${{ github.sha }}/* -DestinationPath BigPictureSwitch-x64-${{ github.ref_name }}.zip
        
        # Package x86 build (was Win32)
        Compress-Archive -Path BigPictureSwitch-x86-${{ github.sha }}/* -DestinationPath BigPictureSwitch-x86-${{ github.ref_name }}.zip
        
        # Package ARM64 build
        Compress-Archive -Path BigPictureSwitch-arm64-${{ github.sha }}/* -DestinationPath BigPictureSwitch-arm64-${{ github.ref_name }}.zip
      shell: pwsh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BigPictureSwitch-x64-${{ github.ref_name }}.zip
          BigPictureSwitch-x86-${{ github.ref_name }}.zip
          BigPictureSwitch-arm64-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## Changes
          
          Automated release for BigPictureSwitch ${{ github.ref_name }}
          
          ### Downloads
          - **BigPictureSwitch-x64-${{ github.ref_name }}.zip** - 64-bit version (Intel/AMD)
          - **BigPictureSwitch-x86-${{ github.ref_name }}.zip** - 32-bit version (Intel/AMD)
          - **BigPictureSwitch-arm64-${{ github.ref_name }}.zip** - ARM64 version (Windows on ARM devices)
          
          ### Installation
          1. Download the appropriate version for your system
          2. Extract the zip file
          3. Run BigPictureSwitch.exe
          
          ### System Requirements
          - Windows 10/11 (version 1709 or later for ARM64)
          - Compatible with Intel/AMD x64, Intel/AMD x86, and ARM64 processors
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}