name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  actions: read

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, Win32, ARM64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{matrix.platform}}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BigPictureSwitch-${{ matrix.platform }}-${{ github.sha }}
        path: |
          ${{ matrix.platform }}/${{ env.BUILD_CONFIGURATION }}/*.exe
          ${{ matrix.platform }}/${{ env.BUILD_CONFIGURATION }}/*.dll
          ${{ matrix.platform }}/${{ env.BUILD_CONFIGURATION }}/*.pdb
        retention-days: 30

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: BigPictureSwitch-*-${{ github.sha }}
        merge-multiple: false
    
    - name: Create Release Packages
      run: |
        # Package x64 build
        Compress-Archive -Path BigPictureSwitch-x64-${{ github.sha }}/* -DestinationPath BigPictureSwitch-x64-${{ github.ref_name }}.zip
        
        # Package Win32 build  
        Compress-Archive -Path BigPictureSwitch-Win32-${{ github.sha }}/* -DestinationPath BigPictureSwitch-Win32-${{ github.ref_name }}.zip
        
        # Package ARM64 build
        Compress-Archive -Path BigPictureSwitch-ARM64-${{ github.sha }}/* -DestinationPath BigPictureSwitch-ARM64-${{ github.ref_name }}.zip
      shell: pwsh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BigPictureSwitch-x64-${{ github.ref_name }}.zip
          BigPictureSwitch-Win32-${{ github.ref_name }}.zip
          BigPictureSwitch-ARM64-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## Changes
          
          Automated release for BigPictureSwitch ${{ github.ref_name }}
          
          ### Downloads
          - **BigPictureSwitch-x64-${{ github.ref_name }}.zip** - 64-bit version (Intel/AMD)
          - **BigPictureSwitch-Win32-${{ github.ref_name }}.zip** - 32-bit version (Intel/AMD)
          - **BigPictureSwitch-ARM64-${{ github.ref_name }}.zip** - ARM64 version (Windows on ARM devices)
          
          ### Installation
          1. Download the appropriate version for your system:
             - Most desktop/laptop users: x64 version
             - Older 32-bit systems: Win32 version
             - ARM-based Windows devices (Surface Pro X, etc.): arm64 version
          2. Extract the zip file
          3. Run BigPictureSwitch.exe
          
          ### System Requirements
          - Windows 10/11 (version 1709 or later for ARM64)
          - Compatible with Intel/AMD x64, Intel/AMD Win32, and ARM64 processors
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}